### ISSUE TITLE
Support Do...Loop Statement

### ISSUE THREAD

**Issue by pakio** [st-tech/refactoring-conductor#3]
# Reference
https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/do-loop-statement

**Comment by yamamoto7** [comment]
@pakio 

According to the MS docs, the syntax for VBS is as follows
```
While condition  
    ' statements
End While  
```

 but ASP seems to support this kind of syntax
```
While condition
    ' statements
Wend
```


In this application, VBS is defined as the following extensions including asp. 
```
const VBScriptFileExtension = `(?i)(.wsf|.vbs|.asp|.inc)$`
```
Therefore, should I support both the two grammars?
